import { BusinessCategory } from "./types";

// Category suggestions based on business type
export const categorySuggestions: Record<BusinessCategory, string[]> = {
  restaurant: [
    "Fine Dining",
    "Casual Dining",
    "Fast Food",
    "Cafe",
    "Bakery",
    "Bar & Grill",
    "Pizzeria",
    "Food Truck",
    "Buffet",
    "Catering",
  ],
  retail: [
    "Clothing Store",
    "Electronics",
    "Furniture",
    "Jewelry",
    "Books",
    "Toys",
    "Grocery",
    "Convenience Store",
    "Department Store",
    "Specialty Store",
  ],
  healthcare: [
    "Hospital",
    "Clinic",
    "Dental",
    "Pharmacy",
    "Laboratory",
    "Physiotherapy",
    "Mental Health",
    "Pediatric",
    "Cardiology",
    "Orthopedic",
  ],
  beauty: [
    "Hair Salon",
    "Nail Salon",
    "Spa",
    "Massage",
    "Beauty Parlor",
    "Barbershop",
    "Cosmetics",
    "Skincare",
    "Makeup Studio",
    "Waxing",
  ],
  fitness: [
    "Gym",
    "Yoga Studio",
    "Pilates",
    "CrossFit",
    "Swimming Pool",
    "Martial Arts",
    "Dance Studio",
    "Personal Training",
    "Sports Club",
    "Fitness Center",
  ],
  automotive: [
    "Car Dealership",
    "Auto Repair",
    "Car Wash",
    "Tire Shop",
    "Auto Parts",
    "Service Center",
    "Body Shop",
    "Oil Change",
    "Bike Service",
    "Garage",
  ],
  "real-estate": [
    "Real Estate Agency",
    "Property Management",
    "Construction",
    "Interior Design",
    "Architecture",
    "Home Inspection",
    "Property Development",
    "Landscaping",
    "Home Staging",
    "Mortgage",
  ],
  education: [
    "School",
    "College",
    "University",
    "Tutoring",
    "Language Classes",
    "Music School",
    "Art Classes",
    "Online Courses",
    "Training Center",
    "Coaching",
  ],
  hospitality: [
    "Hotel",
    "Resort",
    "Bed & Breakfast",
    "Hostel",
    "Travel Agency",
    "Tour Operator",
    "Event Venue",
    "Conference Center",
    "Banquet Hall",
    "Catering",
  ],
  manufacturing: [
    "Factory",
    "Plant",
    "Industrial Unit",
    "Textile Manufacturing",
    "Food Processing",
    "Pharmaceutical Manufacturing",
    "Automotive Components",
    "Electronics Assembly",
    "Packaging",
    "Heavy Machinery",
  ],
  services: [
    "Consulting",
    "Business Services",
    "Legal Services",
    "Accounting & Tax",
    "Marketing Agency",
    "IT Services",
    "Facility Management",
    "Cleaning Services",
    "Security Services",
    "Repair & Maintenance",
  ],
  technology: [
    "IT Company",
    "Software Development",
    "SaaS",
    "Cloud Services",
    "Startup",
    "Product Company",
    "Data & Analytics",
    "AI/ML",
    "Cybersecurity",
    "Tech Support",
  ],
  finance: [
    "Bank Branch",
    "NBFC",
    "Insurance Office",
    "Investment Advisor",
    "Wealth Management",
    "CA Firm",
    "Tax Consultant",
    "Mutual Fund Distributor",
    "Loan Provider",
    "Fintech Company",
  ],
  logistics: [
    "Courier Service",
    "Transport Company",
    "Trucking",
    "Warehousing",
    "3PL Provider",
    "Freight Forwarder",
    "Last-Mile Delivery",
    "Packers & Movers",
    "Cold Storage",
    "Distribution Center",
  ],
  "media-entertainment": [
    "Production House",
    "Recording Studio",
    "Event Management",
    "Advertising Agency",
    "Digital Marketing Agency",
    "Cinema / Multiplex",
    "Gaming Center",
    "Broadcasting",
    "Content Studio",
    "Talent Management",
  ],
  "non-profit": [
    "NGO",
    "Charitable Trust",
    "Foundation",
    "Religious Organization",
    "Social Welfare Group",
    "Community Center",
    "Educational Trust",
    "Environmental Group",
    "Health Charity",
    "Social Impact Organization",
  ],
  other: [
    "General Business",
    "Consulting",
    "Legal Services",
    "Accounting",
    "Marketing",
    "IT Services",
    "Photography",
    "Cleaning Services",
    "Pet Services",
    "Other",
  ],
};

// Service suggestions based on category
export const serviceSuggestions: Record<BusinessCategory, string[]> = {
  restaurant: [
    "Dine-in",
    "Takeout",
    "Delivery",
    "Catering",
    "Private Events",
    "Breakfast",
    "Lunch",
    "Dinner",
    "Brunch",
    "Late Night",
    "Outdoor Seating",
    "Live Music",
    "WiFi",
    "Parking",
  ],
  retail: [
    "In-Store Shopping",
    "Online Shopping",
    "Home Delivery",
    "Gift Wrapping",
    "Layaway",
    "Returns & Exchanges",
    "Custom Orders",
    "Product Consultation",
    "Installation",
    "Warranty Service",
  ],
  healthcare: [
    "General Consultation",
    "Emergency Care",
    "Preventive Care",
    "Diagnostic Tests",
    "Vaccinations",
    "Health Checkups",
    "Telemedicine",
    "Home Visits",
    "Lab Services",
    "Pharmacy",
  ],
  beauty: [
    "Haircut",
    "Hair Color",
    "Hair Styling",
    "Manicure",
    "Pedicure",
    "Facial",
    "Massage",
    "Waxing",
    "Makeup",
    "Bridal Services",
    "Hair Treatment",
    "Spa Packages",
  ],
  fitness: [
    "Personal Training",
    "Group Classes",
    "Yoga",
    "Pilates",
    "Cardio",
    "Strength Training",
    "Nutrition Counseling",
    "Fitness Assessment",
    "Equipment Rental",
    "Locker Facilities",
  ],
  automotive: [
    "Oil Change",
    "Tire Service",
    "Brake Service",
    "Engine Repair",
    "AC Service",
    "Car Wash",
    "Detailing",
    "Battery Replacement",
    "Towing",
    "Roadside Assistance",
  ],
  "real-estate": [
    "Property Sales",
    "Property Rentals",
    "Property Management",
    "Home Staging",
    "Property Inspection",
    "Legal Consultation",
    "Mortgage Assistance",
    "Property Valuation",
    "Interior Design",
    "Renovation",
  ],
  education: [
    "Academic Tutoring",
    "Test Preparation",
    "Language Classes",
    "Music Lessons",
    "Art Classes",
    "Online Courses",
    "Certification Programs",
    "Workshops",
    "Summer Camps",
    "Adult Education",
  ],
  hospitality: [
    "Room Booking",
    "Event Hosting",
    "Catering",
    "Conference Facilities",
    "Travel Planning",
    "Tour Packages",
    "Airport Transfer",
    "Room Service",
    "Laundry Service",
    "Concierge",
  ],
  manufacturing: [
    "Custom Manufacturing",
    "OEM Production",
    "Contract Manufacturing",
    "Quality Testing",
    "Packaging",
    "Logistics Support",
    "Prototyping",
    "Bulk Orders",
    "Private Label",
    "Maintenance Services",
  ],
  services: [
    "Consultation",
    "AMC / Retainer",
    "On-site Services",
    "Remote Services",
    "Training & Workshops",
    "Managed Services",
    "Project Management",
    "Implementation",
    "Support & Helpdesk",
    "Audits & Reviews",
  ],
  technology: [
    "Custom Software Development",
    "Mobile App Development",
    "Web Development",
    "Cloud Migration",
    "IT Support",
    "DevOps Services",
    "Product Maintenance",
    "System Integration",
    "Data & Analytics",
    "Cybersecurity Services",
  ],
  finance: [
    "Account Opening",
    "Loans & Credit",
    "Investment Advisory",
    "Tax Filing",
    "Insurance Advisory",
    "Wealth Management",
    "Financial Planning",
    "Corporate Finance",
    "Compliance & Audit",
    "Retirement Planning",
  ],
  logistics: [
    "Door-to-Door Delivery",
    "Same Day Delivery",
    "Freight Services",
    "Warehousing",
    "Inventory Management",
    "Cold Chain Logistics",
    "Cross-border Shipping",
    "Reverse Logistics",
    "Packing & Moving",
    "Route Optimization",
  ],
  "media-entertainment": [
    "Event Planning",
    "Audio/Video Production",
    "Post Production",
    "Social Media Campaigns",
    "Ad Film Creation",
    "Influencer Marketing",
    "Live Streaming",
    "Photography",
    "Brand Campaigns",
    "Content Creation",
  ],
  "non-profit": [
    "Fundraising",
    "Community Outreach",
    "Awareness Campaigns",
    "Volunteer Programs",
    "Health Camps",
    "Educational Programs",
    "Environmental Drives",
    "Disaster Relief",
    "Advocacy",
    "Donor Management",
  ],
  other: [
    "Consultation",
    "Project Management",
    "Custom Solutions",
    "Support Services",
    "Maintenance",
    "Installation",
    "Training",
    "24/7 Support",
    "Remote Services",
    "On-site Services",
  ],
};

// Get suggested categories based on search query
export function getSuggestedCategories(query: string): BusinessCategory[] {
  const lowerQuery = query.toLowerCase();
  const suggestions: BusinessCategory[] = [];

  const categoryKeywords: Record<BusinessCategory, string[]> = {
    restaurant: ["restaurant", "cafe", "food", "dining", "eat", "meal", "bistro", "pizza", "burger"],
    retail: ["store", "shop", "retail", "shopping", "mall", "market", "boutique"],
    healthcare: ["hospital", "clinic", "doctor", "medical", "health", "pharmacy", "dental"],
    beauty: ["beauty", "salon", "spa", "hair", "nail", "makeup", "parlor"],
    fitness: ["gym", "fitness", "yoga", "exercise", "workout", "training"],
    automotive: ["car", "auto", "vehicle", "garage", "mechanic", "dealership"],
    "real-estate": ["real estate", "property", "housing", "construction", "realtor"],
    education: ["school", "education", "college", "university", "learning", "tutoring"],
    hospitality: ["hotel", "resort", "lodging", "accommodation", "travel"],
    manufacturing: ["factory", "plant", "industrial", "manufacturing", "production"],
    services: ["service", "consulting", "agency", "professional services"],
    technology: ["it", "software", "technology", "startup", "saas", "tech"],
    finance: ["bank", "finance", "loan", "insurance", "investment", "mutual fund"],
    logistics: ["logistics", "courier", "transport", "shipping", "delivery", "warehouse"],
    "media-entertainment": ["media", "studio", "production", "event", "advertising", "marketing"],
    "non-profit": ["ngo", "charity", "non profit", "trust", "foundation"],
    other: [],
  };

  for (const [category, keywords] of Object.entries(categoryKeywords)) {
    if (keywords.some(keyword => lowerQuery.includes(keyword))) {
      suggestions.push(category as BusinessCategory);
    }
  }

  return suggestions.length > 0 ? suggestions : ["other"];
}

